version: '3.8'

services:
    web:
        build: ./challenge
        command: gunicorn --bind 0.0.0.0:1337 app:app
        restart: unless-stopped
        ports:
            - "1337:1337"
    db:
        image: postgres
        restart: always
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: user
            POSTGRES_DB: blog
            POSTGRES_PASSWORD: secret
        volumes:
            - ./database:/var/lib/postgresql/data 

