version: '3.8'

services:
    web:
        build: ./challenge
        command: gunicorn --bind 0.0.0.0:1337 app:app
        restart: unless-stopped
        environment:
            # medium or hard
            DIFFICULTY: hard
            POSTGRES_USER: user
            POSTGRES_DB: blog
            POSTGRES_PASSWORD: secret
        ports:
            - "1337:1337"
        depends_on:
          db:
            condition: service_healthy
        links:
          - db

    db:
        image: postgres
        restart: always
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: user
            POSTGRES_DB: blog
            POSTGRES_PASSWORD: secret
        healthcheck:
          test: pg_isready -U user -d blog
          interval: 2s
          timeout: 1s
          retries: 5
        volumes:
            - ./database:/var/lib/postgresql/data 

